### ISSUE TITLE
UI improvement suggestions

### ISSUE THREAD

**Issue by alex000kim** [iterative/vscode-dvc#1799]
A couple of minor suggestions for UI improvements:
- Autofit column width when double-clicking the border between the columns (like in Excel)
- In the Experiments tab clearly show that filters are applied. Currently, it's very easy to apply a filter, forget about it and then run a few experiments which will/won't be shown in the table depending on the condition of the filter.

**Comment by maxagin** [comment]
> Autofit column width when double-clicking the border between the columns (like in Excel)

Added to Ideas section in this ticket https://github.com/iterative/vscode-dvc/issues/1562

---

> In the Experiments tab clearly show that filters are applied…

This has been implemented I think (ticked: https://github.com/iterative/vscode-dvc/issues/1562).

---

> Since we don't do that, what may do the trick is adding a dashed horizontal line between rows to indicate hidden/filtered rows e.g.:
![image](https://user-images.githubusercontent.com/98249521/175095229-8dd27ca8-c44d-4d23-b4cf-e203d39114de.png)

If I am not wrong, currently we do not hide/filter rows, but thank you @alex000kim  for the feedback!

---

>Also:

- I find "Ready for Git Commit" phrasing a bit confusing because it's a DVC section
- ![image](https://user-images.githubusercontent.com/98249521/175096189-5bd2956f-e85d-492a-b540-0ff56e7b80c2.png)

- When I click the "commit" icon nothing happens (unlike when I click the same icon in the Git section)
- I expected that right-clicking a file would give me some options (like when I right-click in the Git section), but nothing happens

@mattseddon  has this been addressed already?

**Comment by mattseddon** [comment]
Thank you for your feedback @alex000kim. We're incorporating it into our design efforts.
