### ISSUE TITLE
Selecting Experiments redefining

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#1924]
This is an attempt to improve the interaction that is currently in place, also in tight relation with other ongoing work. The main motivation is to provide the user ability (to interact) to work with the row content (for example modifying the cell's info directly in the experiments table) without seeing the unnecessary styles. Any click on the row in the current case will trigger the BG style to appear, this is what we want to resolve.

Full information can be found in [Figma](https://www.figma.com/file/heCQb0FrIfreqn8MsIuV59/Actions-with-Experiments?node-id=656%3A11457). 

TODO

- [x] Select 3rd from the top + Shift and 1st from the top, nothing in between selected. Also by removing one of the two selected both will take unselected status.
- [x] In the case of multiple selections, should not we have Unselect All option in the menu?

**Comment by maxagin** [comment]
Hey folks! Please share with me your comments. I think this is something that will help us to have a bit better user interaction experience. WDYT?

**Comment by shcheklein** [comment]
@wolmir I think it's related to what you do now (multi-row select). What's your take on this? 

@maxagin is it a draft still? We need to make it a bit more realistic - see the table with checkpoints, workspace, etc.

**Comment by maxagin** [comment]
@wolmir what will be happening with expS, when the new branch has been created? Please help me to understand. Thanks

<img width="960" alt="Screen Shot 2022-06-20 at 11 55 43 AM" src="https://user-images.githubusercontent.com/98249521/174640258-238cc280-690f-4ef5-abb6-ba46a85a4a27.png">

**Comment by wolmir** [comment]
What happened here was that DVC created a new branch from that experiment, but nothing happened visually, except for that Toast message.
It makes sense to me, because you can only be working on a single branch at a time anyways.

Is there a need to see them in the table as well?

**Comment by wolmir** [comment]
@maxagin I liked the checkbox design!

What should happen if I select an experiment with child checkpoints?
Only the parent should be selected, or should all its checkpoints be selected as well?

**Comment by wolmir** [comment]
And also:

We already have an experiment toggling feature.
Should this row selection be interpreted as the same thing?
What I mean is: if I select a table row via the checkbox should the corresponding experiment be toggled as well?

**Comment by maxagin** [comment]
>We already have an experiment toggling feature.
Should this row selection be interpreted as the same thing?
What I mean is: if I select a table row via the checkbox should the corresponding experiment be toggled as well?

In terms of the logic, it is the same. However please review the specs and let me know if there is something that functioning differently from what we currently have.

**Comment by maxagin** [comment]
All the above questions are resolved. Thank you @wolmir 👍

**Comment by maxagin** [comment]
Context menu behaviour. @wolmir just for information. (! however, in VSCode it seems like always on the right side :) 

https://user-images.githubusercontent.com/98249521/174659720-89625cea-072e-4681-9276-0bf9c728a8eb.mov

**Comment by wolmir** [comment]
@maxagin Can you add a spec on Figma for an experiment with checkpoints, please?
I would like to know how it should look with only the parent checkbox at the top.

**Comment by maxagin** [comment]
@wolmir yeah. working on it right now

**Comment by maxagin** [comment]
Here we are @wolmir . Take a look and let me know if I have missed something or not.

<img width="949" alt="Screen Shot 2022-06-20 at 4 13 50 PM" src="https://user-images.githubusercontent.com/98249521/174672201-4e9864ed-6ce2-4f4e-b1d9-239de4b1ea0b.png">

**Comment by wolmir** [comment]
Thank you!

**Comment by maxagin** [comment]
> It seems that it should be possible to star a child (checkpoint).

Good. Will create an example

> @shcheklein There are also actions (drop down menu) that could be applied to those also. How will they interact with checkboxes?

I and @wolmir had met and I understood that there are no actions for the checkpoint currently. Let's please clarify this.

**Comment by wolmir** [comment]
@shcheklein At the moment the only option we can apply to multiple rows is to remove them. And this remove option is restricted to the checkpoint tips only.

Should we add the checkbox to the checkpoints anyway?

**Comment by maxagin** [comment]
@wolmir @shcheklein 

> Should we add the checkbox to the checkpoints anyway?

We can add it when we have a case. The point of this question was to clarify that currently, we do not have actions for the checkpoints.

**Comment by shcheklein** [comment]
> Should we add the checkbox to the checkpoints anyway?

No, no need for this.

**Comment by shcheklein** [comment]
> Should this row selection be interpreted as the same thing?

No, for a lot of reasons:

1. since it means then that we need checkboxes for the checkpoints after all +
2. checkbox now select (higlights) the whole row - it would be too heavy for plots toggle
3. it would better to colorize the checkboxes instead (Studio-like)
4. we can't pick > 7 experiments to show plots. It would be strange to apply the same restriction to the remove action for example.

Btw, selecting multiple experiments (including checkpoints) and being able to toggle them on can be potentially handy. Means that we would need checkboxes for them at some point (?)

**Comment by maxagin** [comment]
To include: if the user adds a star to the child, the parent automatically started too.

**Comment by shcheklein** [comment]
> To include: if the user adds a star to the child, the parent automatically started too.

Better to have it a separate state- greyed our star or something.

**Comment by maxagin** [comment]
> Better to have it a separate state- greyed ...

This is can be a bit confusing (discrimination? :) DYT?
I just wanted to point out that if I add a star to the checkpoint, the whole experiment will be stared too.

**Comment by shcheklein** [comment]
> This is can be a bit confusing (discrimination? :) DYT?

Yes, because the reason behind this "the whole experiment will be stared too" is not exactly clear to me. I may want or not to actually have this semantics. 

For simplicity, I would decouple this completely for now- you can start all things independently + some indication to make it friendlier that there are things inside that are starred.

**Comment by maxagin** [comment]
>+ some indication to make it friendlier that there are things inside that are starred

This is the main problem I think. Too many indicators. We will need to find a solution. I would suggest keeping it simple and adding a star to the parent if the child was stared. WDYT?

>it would better to colorize the checkboxes instead

Selecting multiple experiments is one function. Another is being able to toggle them on and off. I do not think we need to mix it. Hmmm...

**Comment by shcheklein** [comment]
> I would suggest keeping it simple and adding a star to the parent if the child was stared. WDYT?

It might be counterintuitive but it complicates the semantics _a lot_ to my mind. E.g. what happens if I toggle that star and there are a few children starred inside? If I star it - does it mean that all experiments are starred? if not, why? Etc.

It's better to skip this altogether and just keep all the things independent for now.

(Btw, checkboxes with three states are very common thing.)

>  do not think we need to mix

That's exactly how I interpreted your answer (that you'd like to mix it now) to @wolmir and that's why I raised this concern. Unless I'm missing something.

**Comment by maxagin** [comment]
>It's better to skip this altogether and just keep all the things independent for now.

Make sense. Thanks !

> (Btw, checkboxes with three states are very common thing.)

Good to know. Thanks !

> That's exactly how I interpreted your answer (that you'd like to mix it now)

The [new version](https://www.figma.com/file/heCQb0FrIfreqn8MsIuV59/1924-%E2%80%A2-Actions-with-Experiments?node-id=729%3A38177) is published. @shcheklein, please take a look.

**Comment by maxagin** [comment]
We will discuss the stars here: Star experiments in table #1676 and I will update the specs with the new info

**Comment by wolmir** [comment]
@maxagin @shcheklein 
This is my plan:

For the Multi-selection PR I will only use checkboxes for rows that can be removed, because that's the only action we have that can be applied for multiple rows.

When I start the Star experiments issue, I'll add the checkboxes for the checkpoints, because then we'll have the "Star selected experiments" option for them.

What do you guys think?

**Comment by shcheklein** [comment]
@wolmir sounds good to me!

**Comment by maxagin** [comment]
@wolmir thank you. Following the original plan.

**Comment by wolmir** [comment]
Just a heads-up: the multi-selection is taking some time because I'm adding a new column for the selection checkboxes, and that entails changing a lot of css rules.

**Comment by mattseddon** [comment]
FWIW 

Adding checkboxes to the view instead of highlighting the row will make the webview feel less native. Highlighting rows to interact with in the explorer tree:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/37993418/175198455-3f8bcea7-2022-4105-a64c-4ef168dfa55e.png">

We also use checkboxes as a toggle in other parts of the app. The usage here contrasts with that usage:

https://user-images.githubusercontent.com/37993418/175198625-92c45a28-7e50-4970-80a5-a1a5a1743856.mov

Finally, this will give three actions to the right of each experiment's name, select for interaction, star and select to display in plots. Seems cluttered.

**Comment by maxagin** [comment]
@mattseddon the main motivation is to provide the user ability (to interact) to work with the row content (for example modifying the cell's info directly in the experiments table) without seeing the unnecessary styles. Any click on the row in the current case will trigger the BG style to appear, this is what we want to resolve.

https://github.com/iterative/vscode-dvc/issues/1924#issue-1275057560

**Comment by wolmir** [comment]
The copy button problem was fixed in the last PR, thanks to Roger's change request.

My personal opinion is that it's ok to use checkboxes for row selections, even in VSCode. I would expect row selection to use checkboxes in a webview table, as a VSCode user I mean.

And later on we'll add the inline params editing which will add another focus/click event to the table cells.

**Comment by mattseddon** [comment]
> @mattseddon the main motivation is to provide the user ability (to interact) to work with the row content (for example modifying the cell's info directly in the experiments table) without seeing the unnecessary styles. Any click on the row in the current case will trigger the BG style to appear, this is what we want to resolve.
>
> https://github.com/iterative/vscode-dvc/issues/1924#issue-1275057560

I understand the motivation and see why you would want to do this. However, in the rest of VS Code, a left-click will highlight what you have clicked on. It does not matter where you click. Also, checkboxes can be toggled from anywhere in a selection:

https://user-images.githubusercontent.com/37993418/175462508-23402dee-4817-4a4a-835e-cd179b99ac2c.mov

There are 4 groups of users that will be introduced to the extension:

1. Familiar with VS Code and DVC
2. Familiar with VS Code but not DVC
3. Not familiar with VS Code but use DVC
4. Not familiar with either.

If we are going to change the behaviour of how rows are selected and move away from the rest of VS Code for one of our webviews then we will have to retrain users in groups 1 & 2 to think differently and expect different behaviour in that one window in the VS Code context. 

We are trying to make the extension appear as native as possible. This will help us with groups 1 & 2 and shows goodwill to MS, who will help us with promotion, bug fixes, etc.

**Comment by shcheklein** [comment]
@mattseddon I would say I completely share your perspective on this (fighting for the native experience as much as we can), but I feel we are stretching the limits I guess. In all the examples you provided elements are "atomic" - one file, one item in the settings, etc. 

Here we have a table. Which has multiple levels of hierarchy - rows, columns, cells + some rows are collapsible + we have already a few states per row - star, toggle on / off plots. This seems to me a scenario that goes beyond the regular one - atomic items. Users need to interact with all these levels, independently. 

Since I didn't try the example w/o checkboxes it's hard for me to tell, but my thinking that tickets like this https://github.com/iterative/vscode-dvc/issues/1383 and similar will start breaking it or complicate the experience with the selection.

We can also analyze how other tables do this - Airtable, Excel, Studio, etc. Or may be VS Code itself has something a bit more relevant for this?

**Comment by maxagin** [comment]
In terms of selecting the rows with a checkbox, all the following platforms are works the same: airtable, wandb and studio. Exactly as proposed here. 

I completely agree with Matt that we better use a native set of tools where it is possible, but to my opinion, this and other similar cases are different as they have multiple actions at the element (the row) and user experience, in this case, dictates a different approach I think.

https://user-images.githubusercontent.com/98249521/175469299-024e4d72-0f58-4b5a-acc3-288a63e0d6d8.mov


https://user-images.githubusercontent.com/98249521/175469304-5f798931-852f-444f-8a71-b59c867f036b.mov


https://user-images.githubusercontent.com/98249521/175469310-53d85228-5a66-4324-a3fe-ceeb09683714.mov

**Comment by mattseddon** [comment]
> Here we have a table. Which has multiple levels of hierarchy - rows, columns, cells + some rows are collapsible + we have already a few states per row - star, toggle on / off plots. This seems to me a scenario that goes beyond the regular one - atomic items. Users need to interact with all these levels, independently.

In our example, the atomic record is the row. Clicking on the row means that you can interact with that row through the context menu. This should not break/interfere with the other ways that the user can interact with the row. I don't see the benefit of doing this through add an additional checkbox. It seems like the main reason for making this change is so we can drop the inline copy button and move to "the user will select and copy the value", this is fine in principle but we do not always have the space to show the full value. Meaning users can/will lose precision when extracting values from the table.

> In terms of selecting the rows with a checkbox, all the following platforms are works the same: airtable, wandb and studio. Exactly as proposed here.

I disagree that the checkbox in Studio behaves the same way as what is proposed here. The checkbox in Studio is used for:

1. Selecting rows to display (loosely equivalent to star behaviour)

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/37993418/175838269-67f0e880-b231-4ebf-9500-a27475a0fb23.png">

2. Selecting rows to display in trends (loosely equivalent to select for plots behaviour)

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/37993418/175838281-9f31e9cf-4ca1-4d85-b901-0e97433257e6.png">

3. Selecting rows to compare directly (we do not have this behaviour)

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/37993418/175838378-bc2c2dd8-890f-4d51-b757-3e2b828c5ba5.png">

4. Selecting a row to run a new experiment (available from context menu)

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/37993418/175838436-4c4a2ae3-fa60-43c9-8c31-5d2a8283521b.png">

They are not used to select rows to interact with through a context menu. There is in fact no context menu available in Studio: 

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/37993418/175838338-f71d128c-2cea-4f01-8979-3ff25360bac2.png">

> We can also analyze how other tables do this - Airtable, Excel, Studio, etc. Or maybe VS Code itself has something a bit more relevant for this?

The Jupyter extension has a [data viewer](https://code.visualstudio.com/docs/datascience/jupyter-notebooks#_data-viewer). Which looks like it uses something similar to the Webview UI toolkit's [data-grid](https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/src/data-grid/README.md) component. I've had a quick play with this and it seems very basic. There are cell-level interactions but not much else:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/37993418/175840357-f58e55b5-f14d-4b1b-a044-958927c857b7.png">


My questions are

1. Why are we not aligning with either the rest of VS Code or Studio?
2. What is the value of removing the inline copy button?
3. Can we reduce the number of elements/concepts needed to interact with experiments?

**Comment by maxagin** [comment]
We want to be able to work with row:
1. modifying the cell's info directly
2. star rows
3. copy info
4. ...

We want to do this without contrast hover styles and unnecessary on-click styles. 

Regarding select on click. 
Where will the user need to click to select the row? 
On the cell with information, which can have some actions also?

...

Would like to refer to this comment: https://github.com/iterative/vscode-dvc/issues/1924#issuecomment-1164773332

>@mattseddon the main motivation is to provide the user ability (to interact) to work with the row content (for example modifying the cell's info directly in the experiments table) without seeing the unnecessary styles. Any click on the row in the current case will trigger the BG style to appear, this is what we want to resolve.

#1924 (comment)

**Comment by shcheklein** [comment]
So, the key here "In our example, the atomic record is the row. " vs "cell is the atomic record". To be more constructive we need a better list of workflows we expect users to do with cells and if those can be replaced with anything

- editing them in the workspace
- show tooltip on hover (now) + on click eventually?
- copy - should be one click or may be two clicks or select with a click + Ctrl+C (cell or icon)

anything else?

My intuition was:

- that any cell-level interactions (even the existing button) are enough to start considering checkboxes, because otherwise users will be missing clicks and copy cells instead of selecting them, etc
- we'll have more things to do with cell values later where click is required (click to show it for example in a tool tip that doesn't disappear, some other things?)

-------


> What is the value of removing the inline copy button?

It's somewhat related, but we can actually keep (and probably should) the button and reconsider this later. No matter we do checkboxes or not.

> Why are we not aligning with either the rest of VS Code or Studio?

Discrepancy between using circles and checkboxes for plots bother me as well though.

My take - both of them are simpler to what we are trying to achieve here. (comes down to the level of granularity again that we need to agree on)

> Can we reduce the number of elements/concepts needed to interact with experiments?

Any specific suggestions in my mind? Do you mean, btw, "actions" (like drop the whole concept of stars, or copy-paste cell, or don't allow multi-select  at all, etc?)

**Comment by mattseddon** [comment]
> We want to be able to work with row:
> 
> 1. modifying the cell's info directly

Experiments are immutable once they are finished the only row that we would be able to inline edit is the workspace record. As the workspace record is the only record that could have inline edit and it will probably never have any multi-select options we should consider disabling "selection" of this row altogether.

> 2. star rows

In order to star multiple rows I would have to click on the checkboxes (right next to the star), select the ones that I want and then invoke the context menu to star the records.... why not just click on the star icons?

> 3. copy info

The existing button works well for this. Mainly because we do not display all of the decimal places for numeric values. See below for an example of where we would lose precision by selecting and copying the value.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/37993418/176063732-4ef82028-5e97-4cbe-a423-4f0520b37c88.png">


> Regarding select on click. Where will the user need to click to select the row? On the cell with information, which can have some actions also?

They should be able to click anywhere on the row (that isn't a copy button). What are the proposed cell-level actions outside of copy that make sense? Having the tooltip activate only through a hover makes sense to me.

> So, the key here "In our example, the atomic record is the row. " vs "cell is the atomic record". To be more constructive we need a better list of workflows we expect users to do with cells and if those can be replaced with anything
>
> editing them in the workspace
> show tooltip on hover (now) + on click eventually?
> copy - should be one click or may be two clicks or select with a click + Ctrl+C (cell or icon)
anything else?

I don't see anything outside of these options. I would not add the show tooltip on click option as this is also not available anywhere else in VS Code.

> Any specific suggestions in my mind? Do you mean, btw, "actions" (like drop the whole concept of stars, or copy-paste cell, or don't allow multi-select at all, etc?)

Drop stars, drop checkboxes, focus around the dot for selection. Leave multi-select how it is implemented now. Give the option to collapse to selected but have it based on dots. This would replace the need for stars altogether. This aligns with the behavior in Studio of selecting up to 7 commits to display together or in trends (plots). Being able to "favourite" more than 7 experiments seems unnecessary and adds clutter to the table.

**Comment by shcheklein** [comment]
> that isn't a copy button.

That alone can annoy, wdyt?

> Having the tooltip activate only through a hover makes sense to me.

More or less, but potentially - click can activate (and pin) tooltips. That's what Studio does because it has more information and we will have too.

> I would not add the show tooltip on click option as this is also not available anywhere else in VS Code.

It's available to some extent for the notifications. Also, we can't completely limit ourselves to the behavior available in VS Code. E.g. recently we were expanding tooltips to add links to them - what would be a solution there if tooltips in VS Code disappear immediately. 

For files we'll want to show more information in those tooltips, we want people to allow to copy all of it or parts of it.

> Drop stars ... This aligns with the behavior in Studio

Studio doesn't have stars semantics and anything close to that yet.

To be honest, I don't quite understand how "up to 7 commits" and "basing these on dots" can solve the problem that stars are solving. Dots are used not to "favorite" something but as a replacement for an "eye" icon - to show / hide on the plots dashboard. Stars have a completely different semantics, right? I can star something (and definitely 7+ experiments), but I don't see all of them on the plots.

> This also gets over the issue of not being able to display stars in the tree.

Most likely we'll have to write our custom tree if needed to accommodate our needs. Again, my feeling is that we go into extremes sometimes (both ends) - let's do a complete SaaS in VS Code and let's not use anything at all that doesn't exist in VS Code.

**Comment by maxagin** [comment]
> both ends

I just tried to propose a more clear solution for the user, also taking into consideration the platform specifics :) Thanks

**Comment by shcheklein** [comment]
I think we agreed on doing stars separately a while ago. I see that they are almost ready. I would go forward and merge them. For now I don't see any better suggestion that could replace them and it's only somewhat related to the things discussed here.

**Comment by wolmir** [comment]
@maxagin @mattseddon @shcheklein @rogermparent 
Checkboxes demo:

https://user-images.githubusercontent.com/1231848/176759316-8adbf549-7764-48af-8383-875763534d97.mov

**Comment by wolmir** [comment]
With shift+click batch selection:

https://user-images.githubusercontent.com/1231848/176775836-fc679373-d0cd-48e6-8fa7-d1a3cf62d26d.mov

**Comment by maxagin** [comment]
Hey @wolmir. Here are a few comments I have collected during my latest review of the exps table:
 

- Select and apply star, appears with a small delay. 
- Select 3rd from the top + Shift and 1st from the top, nothing in between selected. Also by removing one of the two selected both will take unselected status.
- In the case of multiple selections, should not we have Unselect All option in the menu?
- If a column has resided, the hint is showing not in the right place.
<img width="776" alt="Screen Shot 2022-07-04 at 6 06 33 PM" src="https://user-images.githubusercontent.com/98249521/177221200-e437f7e2-bea7-4e8c-95b7-2caf6a39e37a.png">

**Comment by wolmir** [comment]
@mattseddon @maxagin @shcheklein 

What's the correct behavior for bulk selection?

1. Select all checkpoints in the batch
2. Don't select any checkpoints in the batch, unless they all have the same parent.
3. Select only the checkpoints that are visible (expanded) in the table

**Comment by maxagin** [comment]
@wolmir for now, it is: check the checkbox -> Shift (Mac) -> check another checkbox - will select all in between. Or I am missing something? Are you working on the bulk selection?

**Comment by wolmir** [comment]
It's because of this particular comment from Matt: https://github.com/iterative/vscode-dvc/pull/1964#discussion_r912547051

I already fixed the bulk selection bugs, but I want to implement the correct behavior for that case.

**Comment by maxagin** [comment]
Good! Have I answered your question here https://github.com/iterative/vscode-dvc/issues/1924#issuecomment-1175307211 Thank you @wolmir

**Comment by wolmir** [comment]
I don't see how selecting every checkpoint in between would be useful, though. We can only star multiple selections for now

**Comment by maxagin** [comment]
@wolmir 
1. Star / unstar
2. Delete?
3. Unselect selected 

Scenario: I want to star a few expS -> I have selected multiple rows -> I change my mind and need an option to unselect all.

Right?

**Comment by wolmir** [comment]
@maxagin Sorry, I was talking about the multiple selection of rows

See this demo here: https://github.com/iterative/vscode-dvc/pull/1986#issue-1294639122

As you can see, every checkpoint is selected in the range specified by the user.

But the only option the user has at that point is to star/unstar them.
And if you star all the checkpoints of a tip, you might as well just star the tip.

So it seems more useful to select only the tips, because then the remove option is available as well.

**Comment by maxagin** [comment]
> But the only option the user has at that point is to star/unstar them.

And unselect all

**Comment by wolmir** [comment]
Got it, thanks!

**Comment by mattseddon** [comment]
Is the description in this ticket stale?

**Comment by wolmir** [comment]
@iterative/vs-code 
I edited the description by moving items to #1562  and removing the TODOs we agreed not to do.

Given the description that remained, I believe it's safe to consider this done, because the objective was accomplished (moving from line-clicks to checkboxes).

The rest are improvements/fixes (created in #2028 )
