### ISSUE TITLE
Get Started page does not pop up for me

### ISSUE THREAD

**Issue by DavidGOrtega** [iterative/vscode-dvc#1930]
- Follow the Get Started page that pops up!

I do not see that popup not even in fresh installs

**Comment by DavidGOrtega** [comment]
It seems that we rely in `env.isNewAppInstall` which determines that an app is new if current day is the first day it was installed. In my case I had a previous version so I was not able to see the walkthrough. 
Uninstalling and Installing again does not fix it.
Maybe we could add a link to open the walkthrough?

**Comment by shcheklein** [comment]
@DavidGOrtega where do you suggest to add this link? any ideas?

**Comment by mattseddon** [comment]
We have the  `DVC: Get Started` command to show the walkthrough. 

There was a note right next to `Follow the Get Started page that pops up!` saying that you could access the walkthrough this way but it has been removed. 

Do you think this is a docs issue?

**Comment by mattseddon** [comment]
Thanks for clarifying @DavidGOrtega sorry that you had to go through that.

We can remove the "pops up!" text and replace the plain "Get Started" text with a link to the useful commands table. We cannot add a link directly to the command because the listing is shown in this repository as the readme, in the marketplace and finally in-product (the only place the link would work).

We should not remove the popup because a lot of people will simply not read the marketplace listing past the first line. 

I feel like we are actually catering to an edge case because not many people will try the extension, uninstall, and ever come back. If they do it is unlikely that they will closely follow the docs.

cc @jorgeorpinel
