### ISSUE TITLE
Add plots- metric vs hyperparameter values

### ISSUE THREAD

**Issue by alex000kim** [iterative/vscode-dvc#2139]
If I run many experiments, I'd like to be able to select particular experiments and plot how my metric changed vs some parameter/hyperparameter.
Or at the very least, it'd be nice to have an "Export to CSV" button to dump the experiments table result into a CSV file.
(essentially, running `dvc exp show --csv` behind the scene).

**Comment by mattseddon** [comment]
Would you accept parallel coordinates plots (https://github.com/iterative/vscode-dvc/issues/1117) being implemented?

**Comment by alex000kim** [comment]
I'd like to have both as they show slightly different information about the model's behavior :)

**Comment by shcheklein** [comment]
Export to CVS makes total sense, we can also get you a snippet of code on demand I think, at least for Python.

**Comment by alex000kim** [comment]
Yes, a code snippet based on matplotlib or plotly would be nice!

**Comment by julieg18** [comment]
Created a TODO for this issue! Please correct me if either task is misunderstood :) 

- [ ] Add a way to export the experiment table data to a CSV file 
- [ ] Give the user a code snippet on demand for creating a plot that compares a metric and parameter for selected experiments

Starting with the first task, I have a couple questions:

* Do we want to just dump the `dvc exp show --csv` output into a csv result or do we want to try to respect what the current "Experiments" view looks like? For example, drop columns off the csv result if the user has columns hidden in VSCode. 
* Any preference on where this export button goes? I was thinking in the command palette or maybe in the top left corner of the table 🤔 
 
To begin, I'll start off with just adding an action that takes the `dvc exp show -n 3 --csv` result and exports it into a CSV file.

**Comment by shcheklein** [comment]
@julieg18 let's as a first step explore if we can make this happen:

> If I run many experiments, I'd like to be able to select particular experiments and plot how my metric changed vs some parameter/hyperparameter.

I think we the existing Trends engine (custom plots essentially) we can do this w/o too much trouble. And we'll be able may to even generalize them (since trend plot is a metric by step essentially with an ability to follow the updates).

**Comment by julieg18** [comment]
> @julieg18 let's as a first step explore if we can make this happen:
>  > If I run many experiments, I'd like to be able to select particular experiments and plot how my metric changed vs some parameter/hyperparameter.

Sounds good! I'll update the todo and start research!

**Comment by julieg18** [comment]
Looking at the trends plots, we can definitely add params info to our existing plots. Here's a quick example of adding the params into the tooltip ⬇️ Wasn't sure where else the param data could go but I'm not super familiar with Vega. 

<img width="798" alt="image" src="https://user-images.githubusercontent.com/43496356/218820190-8e6e3837-a97b-407a-884e-82fd4e235843.png">

Is this what we're looking for? Or are we looking into creating more custom plots instead of adding onto what we have?

**Comment by julieg18** [comment]
Created a working metric vs param plot using our Trend engine. Here's what it looks like so far (currently, the plots take from selected experiments and hardcoded metrics/params: 

**With lines**

https://user-images.githubusercontent.com/43496356/219512489-46446865-d77a-46da-adec-3be9c5c4d187.mov

**Just marks**

<img width="711" alt="Screenshot 2023-02-16 at 5 38 16 PM" src="https://user-images.githubusercontent.com/43496356/219512390-62b14152-4fd5-4e57-9361-36ab53406ef6.png">

Though after a discussion with Matt, we could also consider a different graph like a scatter plot since the line won't be useful in some cases depending on what the param/metric actually is.

**Comment by julieg18** [comment]
Created a new working section based off selected experiments and fixed metrics/params. Here's a demo:

https://user-images.githubusercontent.com/43496356/220231582-1433e5e1-3087-469f-96cf-a759907c11a9.mov

f we want to continue with this idea, I suppose we'd need to finalize what we want the plots to look like and decide on how users can actually create these custom plots. What does everyone else think? cc @shcheklein

**Comment by shcheklein** [comment]
I like the idea (and I hope, we won't need Trends - they will become one of the possible custom plots). 

Let's create a + Add plot in the section that open quick pick and let's you select plot type (ideally, including the trends one), let you pick X/Y, etc.

**Comment by mattseddon** [comment]
[Q] Is this type of plot something that should be supported via `dvc.yaml`? That would give us the ability to "persist" the plot as a next step in this feature. Top-level plots entry would look something like this:

```
  - Acc vs Lr:
      x: 
        params.yaml: lr
      y: 
        training/metrics.json: [train/acc, test/acc]
      template: scatter
```

Plots would need the ability to support a file with a single entry instead of a list/array.

cc @dberenbaum

**Comment by dberenbaum** [comment]
I think it's more like a visual representation of `dvc exp show/diff` than something that fits within `dvc plots` TBH, and I don't think there is an obvious way I can imagine fitting it into `dvc.yaml` without a substantial effort, so I would lean towards saying no. We tried to add a parallel coordinates plot in `dvc exp show --html`, but this feels like it's more natural outside of the CLI.

Have you discussed with Studio since they also have trends plots? I think it's a hard problem to figure out what users want to see here -- a trend over time, a specific branch of commits, a bunch of experiments based on one commit, etc.?
