### ISSUE TITLE
Data trees: handle better broken DVC files

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#2254]
Let's say I'm editing the project's `dvc.yaml`. If one makes an error in it breaks the side panel (it goes into a loading cycle). From the user perspective it's not clear what is wrong here.

That's what I have in the DVC output channel:

```
version: 0.3.21, 2022-08-24T19:43:02.154Z, pid: 32745] > dvc list . --dvc-only -R --show-json - FAILED with code 1 (288ms)
'./dvc.yaml' validation failed: 2 errors.

expected a dictionary, in stages -> train -> plots -> 0 -> training_metrics, 
line 17, column 7
  16 │   plots:                                                                 
  17 │   - training_metrics:                                                    
  18 │     template: smooth                                                     
```

That's what is happening with the data tree:

https://user-images.githubusercontent.com/3659196/186510107-d8b3300e-0368-44fa-a33f-df0ea41c9a00.mov

That's how error looks like in the table:

<img width="326" alt="Screen Shot 2022-08-24 at 12 48 51 PM" src="https://user-images.githubusercontent.com/3659196/186510181-086445a3-e0dd-476d-a885-6f56a071b153.png">

and

<img width="366" alt="Screen Shot 2022-08-24 at 12 48 45 PM" src="https://user-images.githubusercontent.com/3659196/186510207-706a51b5-35a7-4688-9786-e7cd0ee2e227.png">

In Plots we also don't see any notifications/messages, just some plots are missing.

## Action items:

- [x] In the DVC Tracked / SCM view we should show a message or an icon that something is wrong
- [x] Error message in the table doesn't contain full information
- [ ] Error message design in the table is not good. It blends with the table. Add some padding / margins between the text inside and the border might help, or making it a bit more contrast. That's how a good error message / tip looks like:

<img width="589" alt="Screen Shot 2022-08-24 at 12 55 23 PM" src="https://user-images.githubusercontent.com/3659196/186511094-89c47045-bfdd-4402-8552-d657e32eb759.png">

- [ ] Related/style/minor: Icon in the error message - should it be red one (it's an error after all)? Also, spacing, in a small tooltip like this it looks strange / not noticeable
- [ ] Plots still don't handle errors / don't give info to render? cc @pared?

**Comment by mattseddon** [comment]
I think this and #2255 should both be handled by DVC in the same way that the same situation is for `plots diff` and `exp show`. 

Note: I just checked out how `data status` deals with this situation and it also throws an unexpected error.

**Comment by shcheklein** [comment]
Any specific suggestion on how it should be handled by DVC?

I'm not sure this is a DVC problem. `status` can't do partial results. Or do you mean that it should be throwing an "expected error" in this case?

Anyways, as we discussed we should be prepared for unexpected errors as well, right?

**Comment by mattseddon** [comment]
> Any specific suggestion on how it should be handled by DVC?
>
> I'm not sure this is a DVC problem. status can't do partial results. Or do you mean that it should be throwing an "expected error" in this case?

Do their best to parse the yaml file and return as much data as possible. Basically, behave the same way as `exp show`. In the worst-case scenario return an object with an error key/code so that we know how to act.

> Anyways, as we discussed we should be prepared for unexpected errors as well, right?

We no longer retry on an unexpected error so we will only try to update the data when the file is edited/saved. The only missing piece should be displaying some error in the tree. When we move to `data status` it should appear empty under these circumstances.

**Comment by skshetry** [comment]
VSCode could show stale tree data and show warnings/errors.

It might fail on initial startup though, so definitely something that should also be fixed in dvc. I think `dvc data status` should not fail, although here the output may end up being misleading. Rather than skipping what failed, we could skip any errored out `dvc.yaml` from all of `HEAD`/`index` and from workspace.

**Comment by mattseddon** [comment]
if you could return which files have failed to parse we can make the user aware of that and indicate that the results will be misleading.

**Comment by skshetry** [comment]
Yes but that means `dvc data status` output might be misleading. 😂

**Comment by skshetry** [comment]
Anyway, please open an issue in DVC for `data status`.

**Comment by shcheklein** [comment]
> Do their best to parse the yaml file and return as much data as possible

my take this would be very hard to do. And it will be more like an improvement. We still need to show a proper message that at the moment some files are broken, or something like this. It would be good for us to have that list. If we can agree on the error message format we can parse it out I think?

**Comment by mattseddon** [comment]
> Do their best to parse the yaml file and return as much data as possible

I was not functioning at 100% yesterday. It was a bad idea. I still think the command shouldn't fail. We should be returned something of the form:

```
{ 
    "error" { "type": string, "msg" } 
}
```

I'll raise an issue. In the code, we can decide what to do based on the type of error returned.

**Comment by pared** [comment]
@shcheklein you are correct that renderer does not handle the errors yet. 
Related: iterative/dvc#7692

**Comment by shcheklein** [comment]
@mattseddon 

>I was not functioning at 100% yesterday. It was a bad idea. I still think the command shouldn't fail. We should be returned something of the form:

I feel it goes into a broader discussion (how DVC communicates errors in case of `--json`). I'm not sure what the right answer there (feels that 0 error code is also wrong, probably can `--json` + `--no-fail` or something. 

I think we don't depend much on this decisions? We still should handle, show error message, etc, etc. wdyt?

**Comment by mattseddon** [comment]
We are currently stuck because we need retries for lock-based errors, e.g when an experiment is running and `status` fails. Once we can consume `data status` we will be able to remove retries (at least temporarily). 

This still leaves us with the problem of behaving differently given different errors. 

If we are simply going to fail and pass the message on to the user then ok, we can do that. I can get started as soon as we switch over to `data status`.

However, there are going to be cases where we want to behave differently given the error(s) that DVC provides. I do not want to go down the route of trying to parse/query error messages to give different behaviour. Especially when we run into so many 255s. 

At the very least we need to start grouping these errors into specific codes but IMO a consistent approach would be best. `exp show` took the approach of providing errors within the data and not failing, I assumed that `plots diff` and `data status` will do the same for the same reasons.

**Comment by mattseddon** [comment]
[This PR](https://github.com/iterative/vscode-dvc/pull/2301) will start to address some of the extension's error handling issues.

### Demo (WIP)

https://user-images.githubusercontent.com/37993418/187591337-be8184bd-9576-4a54-b4d9-704a50987e89.mov

@shcheklein from the OP:

> - [ ] In the DVC Tracked / SCM view we should show a message or an icon that something is wrong

The above PR will add an error to the DVC Tracked tree with an error (shown in demo), we will leave the SCM tree empty as we cannot show an error in an obvious way (limitation of the API).

> - [ ] Error message in the table doesn't contain full information

This is what is provided by `exp show`. If we want to change it we will need to open a new DVC issue.

> - [ ] Error message design in the table is not good. It blends with the table. Add some padding / margins between the text inside and the border might help, or making it a bit more contrast. That's how a good error message / tip looks like:
> - [ ] Related/style/minor: Icon in the error message - should it be red one (it's an error after all)? Also, spacing, in a small tooltip like this it looks strange / not noticeable

I originally matched the error tooltip in the webview to the tooltip for the experiments tree (both shown in demo). We are unable to make anything in that tooltip red. IMO the fact that these are displayed as hints above red text is enough. The big red ! gives a good enough indication that something is broken. I chose consistency but am happy for this to be updated.

> - [ ] Plots still don't handle errors / don't give info to render? cc @pared?

Need to wait for https://github.com/iterative/dvc/issues/7692 to be able to address this.
