### ISSUE TITLE
Multiple commits: show commit information, other improvements

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#2458]
After implementing multiple commits logic we can start improving the UX a bit.

Hash as a name is not informative. It's not even clear if that is a commit or an experiment.

For commits we have more information - author, commit name, tags, etc.

I think if we have tags, we should show them. If not, we should show the commit message (any part of the message is better vs hash).Tooltip should include everything else - author names, etc. Eventually going into a direction of tooltips that GitLens has.

**Comment by shcheklein** [comment]
Related https://github.com/iterative/vscode-dvc/issues/2476

**Comment by mattseddon** [comment]
Related to #2458

**Comment by julieg18** [comment]
From what I understand about the `dvc exp show` output, the output provides us with the commit `sha` but no other information about the commit. Two ways I looked into for getting the commit information is the [Github REST API](https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28) and using [`git log` with a `--pretty`](https://git-scm.com/docs/pretty-formats) flag. 

The attempt I'm currently working on is using `git log` since we already have logic set up for running internal git commands. I was thinking of adding on to our rendered experiments data, including the needed commit data as well 🤔

**Comment by shcheklein** [comment]
@julieg18 thanks for the update. git CLI sounds good to me.
