### ISSUE TITLE
Showing wrong info for non-linear flexible plots

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#2516]
Now that https://github.com/iterative/vscode-dvc/issues/1757 has been closed, I can see linear flexible plots with nice formatting 🙌 :

<img width="1121" alt="Screen Shot 2022-10-03 at 12 13 59 PM" src="https://user-images.githubusercontent.com/2308172/193627458-31d244ed-eabf-476e-9de6-9335baa0af01.png">

However, the confusion matrix above is not being shown as expected since it is supposed to be comparing train and test for each revision. Here's what it looks like outside of VS Code:

<img width="1383" alt="Screen Shot 2022-10-03 at 12 12 17 PM" src="https://user-images.githubusercontent.com/2308172/193627629-7ab2c2dc-a2f5-4b48-a757-ebab675887c7.png">

VS Code seems to be combining train and test into one confusion matrix.

**Comment by dberenbaum** [comment]
cc @pared

**Comment by mattseddon** [comment]
Can you share the project please @dberenbaum.

**Comment by dberenbaum** [comment]
🤦 Sorry about that: https://github.com/dberenbaum/example-get-started/tree/flexible_plots

**Comment by mattseddon** [comment]
I have to concatenate the required data into the rev field in order to render the confusion matrix as expected: 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37993418/193736883-ec684669-cb2d-477d-9a93-ce48e5037147.png">

This has raised another issue:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37993418/193736952-49b172fb-1d79-42ca-9ff7-b9a02469d9f3.png">

Even regular-sized confusion matrices are too small once we get to 4 revisions (cc @sroy3).
