### ISSUE TITLE
Clicking outside the table removing checks from the checkboxes

### ISSUE THREAD

**Issue by maxagin** [iterative/vscode-dvc#2528]
https://user-images.githubusercontent.com/98249521/193937449-1999a02e-6916-4534-9cfa-e752b5eddbf2.mov

**Comment by sroy3** [comment]
Did some digging as to why this was added in the first place (https://github.com/iterative/vscode-dvc/pull/1906). It actually comes from a comment I had previously made (https://github.com/iterative/vscode-dvc/pull/1906#issuecomment-1161683746). If I remember correctly,  it's because I found it annoying if you select a lot of rows that you have to deselect them manually. Clicking outside the table is not the way to go as this feels broken and can make you accidentally unselect your rows. But maybe we should either add a button to quickly unselect rows (maybe something like select all / deselect all), or keep the current behaviour and add a confirmation before unselecting the rows (which might be a little less obvious).

**Comment by sroy3** [comment]
> Did some digging as to why this was added in the first place (#1906). It actually comes from a comment I had previously made ([#1906 (comment)](https://github.com/iterative/vscode-dvc/pull/1906#issuecomment-1161683746)). If I remember correctly, it's because I found it annoying if you select a lot of rows that you have to deselect them manually. Clicking outside the table is not the way to go as this feels broken and can make you accidentally unselect your rows. But maybe we should either add a button to quickly unselect rows (maybe something like select all / deselect all), or keep the current behaviour and add a confirmation before unselecting the rows (which might be a little less obvious).

Like @julieg18 mentioned in her PR, there are already some ways to unselect all rows (esc and context menu). So we should be good with that.
