### ISSUE TITLE
Top-level plots are not updated while the experiment is running

### ISSUE THREAD

**Issue by daavoo** [iterative/vscode-dvc#2851]
> From memory we get the files to watch from the keys of the plots data. This means that top-level plot keys like dvclive/dvc.yaml::dvclive/plots/metrics/foo/bar.tsv will break the current process. Needs an update.

_ @mattseddon

**Comment by mattseddon** [comment]
@daavoo I found a quirk with the data that we receive from `plots diff`. The data takes the format:

```
type PlotsOutput {
  [key: string]: Plot[]
}
```

I thought that the key could always be boiled down to a path but it can't (e.g `'dvc.yaml::Precision-Recall'`). In order to get the paths to watch I have to interrogate all of the datapoints for each plot to pull the filename out of the individual `dvc_data_version_info` dicts. That is really inefficient and the same cannot be done for images. Would it be difficult to add a filename key close to the top of the `plots diff` output?

**Comment by daavoo** [comment]
> That is really inefficient and the same cannot be done for images. Would it be difficult to add a filenames key/list close to the top of the plots diff output?

I think it should be possible. Will take a look and get back to you.

**Comment by dberenbaum** [comment]
Related to https://github.com/iterative/studio/issues/4686. @mattseddon You may want to watch there since it may simplify this for you.
