### ISSUE TITLE
Global / Auto unrequested Workspace change

### ISSUE THREAD

**Issue by SoyGema** [iterative/vscode-dvc#3140]
Thanks for bringing continuous verbosity to DVC Workspace Setup. 👍 

**Description**

Unrequested DVC Workspace setup (from **Auto** to **Global** and Global to Auto)change during the execution of `dvc exp run ` in [Neural Machine translation](https://github.com/SoyGema/Neural-Machine-Translation) Tutorial.  This seems to slow down the experiment launch. Note that in the end, it works correctly 

**Setup**
Inside virtual environment. Config Auto .

* DVC VSCode extension version `v0.5.37`
*  DVC Version `2.38.1`
* DVCLive Version `1.3.1`

**Comments / Benchmarking**

Please note that this behavior doesn´t appear in [other demos](https://github.com/SoyGema/Fast-Experiment-tracking-Demo) that don´t include pipelines, so somehow pipelines  Workspace Setup might be involved? Me trying to guess a direction to check here 

https://user-images.githubusercontent.com/24204714/213997970-0e0267cb-b70e-4e35-88ec-8c4a5cfd6bab.mov

Have a nice day! 🥇

**Comment by shcheklein** [comment]
Very weird indeed. We'll look into this.

Q: why do you use `dvc exp run` from the command line? Any specific reason for that, does Run action work in VS Code?

**Comment by SoyGema** [comment]
A: I guess the choice comes from multiple dimensions 

- **Feedback from CSE** regarding teaching about the project: simplify pipeline Demo in order to be more easily understood by developers. 
- **Heavy usage.** Once I'm in the code, I´ve been using `dvc exp run `with each stage to debug and control it.
- **Outputs**

Please find the video above run from the table. Still shows the unrequested dance, and gives more info (Analyzing file signal )

https://user-images.githubusercontent.com/24204714/214243003-367fc183-2b36-4b42-9507-1a1c6a025c44.mov

Thanks for the time dedicated to this !

**Comment by mattseddon** [comment]
Hi @SoyGema,

I am trying to recreate the error using the [Neural-Machine-Translation](https://github.com/SoyGema/Neural-Machine-Translation) repo. I haven't been able to workout how to setup the virtual environment for this project. I can see that you have a `.venv` folder checked in to Git but it does not contain the required packages.

`pip install -r requirements.txt` fails with `ERROR: Invalid requirement: "'dvc[s3]'" (from line 12 of requirements.txt)`

After making the required update the install then fails with: 
```
ERROR: Could not find a version that satisfies the requirement conda==4.14.0 (from versions: 3.0.6, 3.5.0, 3.7.0, 3.17.0, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.7, 4.0.8, 4.0.9, 4.1.2, 4.1.6, 4.2.6, 4.2.7, 4.3.13, 4.3.16)
ERROR: No matching distribution found for conda==4.14.0
```

Can you provide me with some setup instructions please 🙏🏻.

Thanks,

**Comment by SoyGema** [comment]
Hello, @mattseddon thanks for the time dedicated to this. 👍 
You are right, the reproducibility is outdated.
What I think at this point is that a now unexisting release of [conda](https://github.com/conda/conda/issues/11653) was used by my past self  for this. 

I'm reproducing the project **from scratch** in another Machine `MacBook Pro M1 Ventura` with `conda==4.3.16 ` using `Python3.9 `,  Could you give it a try when you have the time ?
You can find here the new [requirements.txt ](https://github.com/SoyGema/Neural-Machine-Translation/blob/main/requirements.txt) file . So please activate `.venv `environment and install new `requirements.txt`


**IMPORTANT IF YOU ARE USING MAC**
 There have been some [founded weepings](https://developer.apple.com/forums/thread/700906) about library support `tensorflow-text` for MAC.  Please follow [this ](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/blob/main/tutorials/text/text.md)  from point 2 for installing it as it is needed and currently out of the requirements file. Check that you have `tensorflow-macos==2.9.2` installed ( this shall come from requirements.txt ) , you will probably have to install tensorflow-metal (given n point 2). Check consistency of tensorflow-macos with the python version  , as if not It might cause errors. Mind versioning ! 

**IF YOU  ARE NOT USING MAC** 
You can install tensorflow-datasets via pip . The current project is reproducible in 4.6.0 version
`!pip install -q -U tensorflow-text tensorflow`

NOTE :
If you find any error in the form of the snippet shown above , please check that pip and setup tools are updated via `python3 -m pip install --upgrade pip `and `pip install --upgrade setuptools`
```
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/xf/p80m2cnn1p933tws66bc2nzh0000gn/T/pip-install-m4fltmsn/ruamel-yaml-conda_137a135f422c44cea138b475d52256a8/setup.py", line 35, in <module>
          ext_modules=cythonize(extensions),
        File "/Users/matt/Library/Python/3.9/lib/python/site-packages/Cython/Build/Dependencies.py", line 970, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/Users/matt/Library/Python/3.9/lib/python/site-packages/Cython/Build/Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/Users/matt/Library/Python/3.9/lib/python/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: 'ruamel_yaml/ext/_ruamel_yaml.pyx' doesn't match any files
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

Please let me know if you are finding this during requirements install 

```
  WARNING: The script WHATEVER is installed in '/Users/matt/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

Hope this helps!!!! 

Thanks for this, I will definitely add the instructions to the README.md in a more detailed and  rigorous manner

**Comment by mattseddon** [comment]
I ran into a few issues while trying to get up and running. I am on M1.

Firstly I could not get the virtual environment to work whilst it was checked in to Git. I ended up deleting the folder and adding it to a new `.gitignore` file. I've raised a PR to make this change permanent here: https://github.com/SoyGema/Neural-Machine-Translation/pull/3

[this](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/blob/main/tutorials/text/text.md) fell over in a few places for me. I had to add another `requirements.txt` file to install `tensorflow-metal==0.5.0`, the `tensorflow-text` wheel build script then asked me to install `bazel 5.3.0` (not 5.1.1) and then fell over with some unintelligible error. I eventually gave up and downloaded the 2.9 wheel from [here](https://github.com/sun1638650145/Libraries-and-Extensions-for-TensorFlow-for-Apple-Silicon/releases).

That worked once I installed the wheel into the new virtual environment before reinstalling the original requirements.

Trying to run an experiment then fell over because I don't have access to the dvc remote or required datasets. I do think that the process gets far enough to show that the issue with switching between global and auto was resolved by removing the virtual environment from Git:


https://user-images.githubusercontent.com/37993418/214981461-cbcbbb7d-fdef-43dd-81d6-bd922c18fcf7.mov

The reason that I think this change is the cause:

- Files checked into Git can fire watchers when an experiment starts, we watch the virtual environment to see when we need to run/re-run the setup process. This unnecessary call to setup with trigger CLI discovery which could cause the behaviour shown.
- https://github.com/SoyGema/Fast-Experiment-tracking-Demo does not have the virtual environment checked in, nor do any of the other demo projects that the company uses (I have never seen this behaviour before).

Would you be able to see if you can recreate the issue once the virtual environment has been purged from Git?

**Comment by SoyGema** [comment]
Hey!
Thanks. Your intuition is correct. Small video to prove this. 
This exploration raised some important aspects regarding reproducibility and best practices for the project which lead to this. https://github.com/SoyGema/Neural-Machine-Translation/issues/4

I consider the main construct that lead to this issue solved, therefore Im closing this. I might come in the future to ask for testing once the data is in the registry.
Thanks for the time dedicated to this issue. Have a nice day. 





https://user-images.githubusercontent.com/24204714/215452391-f31705c2-95bb-4463-8608-0d6ff220eee4.mp4
