### ISSUE TITLE
Plots from temporary experiments are first updated when finished

### ISSUE THREAD

**Issue by ostromann** [iterative/vscode-dvc#3436]
If you start a temporary experiment by using `dvc exp run --temp`, the plots will show the metrics of the last completed experiment in the workspace instead of the current temporary experiment.
When the temporary experiment finishes, it disappears from the plots and needs to be re-added, showing the actual metrics then.

It would be good to see the metrics of currently running temporary experiments in realtime in the Plots section.

**Comment by mattseddon** [comment]
Hi @ostromann,

Thanks for raising the issue.

There is a limitation in that DVC does not collect metrics for experiments running outside of the workspace (unless they are checkpoint based). This is being actively worked on at https://github.com/iterative/dvc/issues/8478. We have #3178 in this repo for the subsequent work needed.

By any chance are you using DVCLive to log metrics?

**Comment by ostromann** [comment]
Thanks!
Yes, I do use DVCLive to log metrics.

**Comment by mattseddon** [comment]
Ok, as a temporary workaround, you can get live updates by connecting to Studio, switching from `--temp` to `--queue` and starting the queue with the extension. Live updates will show up in Studio for all experiments run from the queue.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/37993418/224280186-8a5beabe-cd0a-4c06-9a8c-a44701081d8b.png">

Docs are [here](https://dvc.org/doc/studio/user-guide/projects-and-experiments/live-metrics-and-plots). 

Hope this helps. LMK if you get stuck.

Note: I think it you start `dvc exp run --temp` with the environment variables `STUDIO_TOKEN` & `STUDIO_REPO_URL` included then you should still get live updates.

**Comment by shcheklein** [comment]
> As far as I understand, that rules out DVC Studio for me, right now

There is an on-prem option for Studio (it's paid, but just in case your org can consider this). In no way saying we are not fixing this, we are working on this, it's prioritized.

**Comment by mattseddon** [comment]
@dberenbaum this issue is why we want to prioritise live plot updates for experiments running in the queue/temp directories. Collecting data for the separate queue/temp revisions would be problematic for the reasons mentioned in #3676. We would have to re-implement the "merging" logic, from DVC in the extension, make separate CLI calls, cache data etc. This would be a significant effort in the extension and IMO less valuable than implementing the ability to call plots diff with these revisions in DVC. I'd be happy to implement it on the DVC side if we decide it would be the best way forwards.

LMK what you think, 🙏🏻.

**Comment by mattseddon** [comment]
Hi @ostromann,

I realise it has been a long time since we gave you an update on progress. The good news is that the changes required to get live updates for plots running outside of the workspace were released with DVC `2.58.1`. In version `0.9.0` of the extension, you can select experiments running outside of the workspace and view their plots.

Thanks for your patience. `0.9.0` should be in the marketplace soon.
