### ISSUE TITLE
Consider relaxing the lower bound for "The extension cannot initialize ... upgrade to the most recent version of the CLI", or possibly improve the prompt?

### ISSUE THREAD

**Issue by blakeNaccarato** [iterative/vscode-dvc#3773]
I know that you tend to avoid breaking users with DVC version upgrades, but to be safe I tend to pin DVC in my projects. I try to roll up these pins roughly monthly, but this cadence is still too slow to prevent the DVC extension from complaining "please upgrade to the most recent version of the CLI". I think this lower bound may be too aggressive?

Is it reasonable to relax this bound, perhaps allowing the extension to initialize even for CLI versions from up to (at most) three months ago? I understand that this is a tradeoff between development velocity and keeping the extension/CLI in lockstep. So if the decision is to keep the user close to current (less than a month from latest version), the user experience should be improved with regard to this "nag" notification. Maybe there can be a clickable prompt in this popup to go ahead and upgrade the installed DVC CLI for you?

Of course the issue here also lies with how the VSCode extension experience is best when not bothering to manually manage extension versions. As soon as a user rolls back an extension version to get around such a prompt, it's easy to forget to upgrade it ever again, which is probably not the intended effect of an overly-picky CLI bound.

Thank you for your consideration! Documentation of the recommended user flow for VSCode users (use `pipx`, just use the desktop executable, do a particular thing) would also mitigate this even if no changes are made to the prompt/bound.

**Comment by mattseddon** [comment]
Thanks for bringing this up and taking the time to share your feedback.

> Is it reasonable to relax this bound, perhaps allowing the extension to initialize even for CLI versions from up to (at most) three months ago?

We do leave the min version alone unless we absolutely have to bump it and what has been happening recently is not normal. Every time we bump the min version we do it specifically for a breaking change. 

Over the last two months, there have been major improvements/breaking changes made to the CLI specifically for the extension. These can be found in the CHANGELOG by searching for `Bump min DVC version`. Each entry should give a rough reason for the change and a link to the PR so you can investigate and make a decision as to whether or not you want to upgrade the version of DVC for that change or stay on an outdated version of the extension for the foreseeable future.  

Relaxing the lower bound in these instances would lead to the extension simply not working without a significant effort being made by the team. For example, we completely changed the data type for `exp show` in #3665 so that we can provide users with live metrics for experiments running outside of the workspace (queue/temp directories).

We're a small team and we feel like we can provide more user value by not focusing on keeping the extension backwards compatible with older versions of the CLI.

Hope this makes sense.

> Maybe there can be a clickable prompt in this popup to go ahead and upgrade the installed DVC CLI for you?

We are actually already working on this at https://github.com/iterative/vscode-dvc/issues/3434. We'll be directing users to the DVC section of our new setup page which will provide more value than the current UI/UX.

> Of course the issue here also lies with how the VSCode extension experience is best when not bothering to manually manage extension versions. As soon as a user rolls back an extension version to get around such a prompt, it's easy to forget to upgrade it ever again, which is probably not the intended effect of an overly-picky CLI bound.

For managing outdated extensions consider using this functionality: https://code.visualstudio.com/docs/editor/extension-marketplace#_update-an-extension-manually (you will still have to set a reminder/process to do it at the same time you roll up your pins monthly). One step further would be to introduce a [devcontainer](https://code.visualstudio.com/docs/devcontainers/containers) per project.

> Thank you for your consideration! Documentation of the recommended user flow for VSCode users (use pipx, just use the desktop executable, do a particular thing) would also mitigate this even if no changes are made to the prompt/bound.

We purposefully try to not have an opinion about this and let the user decide how they want to setup their project(s). Again the details (coming soon) in the custom settings page will help users to readily debug when things don't work.

**Comment by blakeNaccarato** [comment]
Thanks for taking the time to elaborate on these points! I do like the generally unopinionated philosophy that Iterative takes, and I can certainly accept some uncertainty regarding recommended approaches for the benefits of development velocity and responsiveness!

The `@outdated` filter is especially helpful, I will have to add that to my periodic manual update workflow. And thanks for the devcontainer advice. I have just found some related documentation for this in your org at the following links:

- [Example use case: Shared development server](https://dvc.org/doc/use-cases/fast-data-caching-hub#example-shared-development-server)
- https://github.com/iterative/features: Looks like a basic devcontainer setup including DVC?

Alright, I'll close this issue then, perhaps as "not planned" (feel free to change). I see how relaxing lower bound requirements for the extension would not be feasible here.
