### ISSUE TITLE
error: index is locked

### ISSUE THREAD

**Issue by dberenbaum** [iterative/vscode-dvc#4111]
I think both me and @shcheklein have encountered this issue. The error is from git/dvc but I have only seen it in vs code. Not sure how to reliably reproduce, but maybe we can think about ways to reduce calls that require the git lock.

```
[version: 1.0.3, 2023-06-14T20:58:40.397Z, pid: 75883] > /Users/dave/miniforge3/envs/dvc/bin/dvc exp run --queue -S params.yaml:train.arch='resnet18,shufflenet_v2_x2_0' -S params.yaml:train.fine_tune_args.base_lr=range(0.001,0.01,0.001) - FAILED with code 255 (1389ms)
Queueing with overrides '{'params.yaml': ["train.arch='resnet18,shufflenet_v2_x2_0'", 'train.fine_tune_args.base_lr=0.001']}'.

Queued experiment 'after-rook' for future execution.

Queueing with overrides '{'params.yaml': ["train.arch='resnet18,shufflenet_v2_x2_0'", 'train.fine_tune_args.base_lr=0.002']}'.

Queued experiment 'cruel-fibs' for future execution.

Queueing with overrides '{'params.yaml': ["train.arch='resnet18,shufflenet_v2_x2_0'", 'train.fine_tune_args.base_lr=0.003']}'.

Queued experiment 'silky-lays' for future execution.

ERROR: unexpected error - the index is locked; this might be due to a concurrent or crashed process
```

**Comment by shcheklein** [comment]
@pmrowla do we / can we retry operations on a locked Git index?

**Comment by pmrowla** [comment]
We don't retry any operations on a locked git index. We could consider trying to sleep and then retry after some timeout, but it would be helpful to know where this issue is actually happening. We can't just add a generic retry for every git operation in DVC because some of them depend on state (where retrying whatever operation tried to read the index actually requires rolling back some # of git operations and then rerunning the entire set of operations)

**Comment by mattseddon** [comment]
Do we want to run all of our Git processes with `GIT_OPTIONAL_LOCKS=0`?

**Comment by mattseddon** [comment]
@dberenbaum @shcheklein please let me know if you run into this again.
