### ISSUE TITLE
Filtering Queued Experiments

### ISSUE THREAD

**Issue by mattseddon** [iterative/vscode-dvc#4317]
It appears that queued experiments no longer drop metrics from their records:

<img width="1728" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/e1bd2c04-95d1-4866-956a-3faf9fce3d76">

This has some implications for filtering within the extension. We previously bypassed filtering queued experiments on metrics with this simple workaround: https://github.com/iterative/vscode-dvc/pull/1732

These experiments will now be filtered based on the incorrect(?) metrics that they display.

@dberenbaum is this a bug in DVC or expected? Should we care about working around this in a different way?

**Comment by dberenbaum** [comment]
🤔 I can't recall that we were ever doing this intentionally, although it makes sense. @daavoo @pmrowla Do you remember this or know if anything changed?

**Comment by pmrowla** [comment]
Queued experiments technically do have metrics (assuming that a metrics file from a previous `repro` or `exp run` exists in the workspace at the time the user queues the experiment). We used to manually drop metrics values at the `exp show` CLI UI level, this probably got lost when we implemented the caching + new json format.

If it's preferred that we drop them in DVC before returning the json output we can do that, but I'm not actually sure whether or not we should have been doing it in the first place (since the queued exp can actually contain prior existing metrics values)

**Comment by dberenbaum** [comment]
> We used to manually drop metrics values at the `exp show` CLI UI level, this probably got lost when we implemented the `exp show` caching + new json format.

Can we go back to this? Were we ever dropping them from json output? Not sure how else metrics were being dropped before in the VS Code extension otherwise. If we do it in the CLI, I think it would be good to drop them in json also if it's not a ton of effort.

**Comment by pmrowla** [comment]
They were dropped from the old json output because the old json output was based on the CLI output (and not the actual underlying data).

It should also be noted that dropping the values makes `exp show` inconsistent with `dvc metrics show <queued exp>` - `dvc metrics` will always output the underlying values (and not drop them for queued exps)

**Comment by dberenbaum** [comment]
> It should also be noted that dropping the values makes `exp show` inconsistent with `dvc metrics show <queued exp>` - `dvc metrics` will always output the underlying values (and not drop them for queued exps)

This was already the case before, right? I don't feel strongly about whether it should be in json or if vs code should just drop metrics for any queued experiments. I can see how it's awkward to see them for queued experiments, though.

**Comment by pmrowla** [comment]
> This was already the case before, right? I don't feel strongly about whether it should be in json or if vs code should just drop metrics for any queued experiments. I can see how it's awkward to see them for queued experiments, though.

Yes, this was always the case before.

**Comment by dberenbaum** [comment]
Thanks @pmrowla! Not sure if this is the "right" behavior, but at least it gets us back to where we were for now.
