### ISSUE TITLE
After experiment is done it's not select for plot anymore

### ISSUE THREAD

**Issue by shcheklein** [iterative/vscode-dvc#4491]
It stays on the workspace. It means when I run a new experiment the previous plotted one just disappears underneath me.

**Comment by mattseddon** [comment]
I cannot recreate this. 

https://github.com/iterative/vscode-dvc/assets/37993418/be899e51-605c-4e18-840a-346410daacf5

BUT if you are running experiments using the queue then they will not be selected by default.

**Comment by shcheklein** [comment]
Okay, I think I know where it comes from. This is a `dvclive` only setup. When it runs only in workspace initially and creates an experiment only at the end. Can we keep the same behavior as we have for the regular exps as we run them? I mean at the final stage, select automatically the newly created experiment.

**Comment by mattseddon** [comment]
This behaviour was dropped in https://github.com/iterative/vscode-dvc/pull/3965 (on purpose). The code was brittle and difficult to maintain.

**Comment by mattseddon** [comment]
When DVCLive is running an experiment without DVC it has the name at the same stage as it creates the signal file for the extension:

https://github.com/iterative/dvclive/blob/main/src/dvclive/live.py#L173-L174

I can raise a PR to update what is written to the signal file but will still have to do some messing around on the extension side because there is no minimum requirement for DVCLive and I don't think there should be one either.

**Comment by shcheklein** [comment]
> but will still have to do some messing around on the extension side because there is no minimum requirement for DVCLive and I don't think there should be one either.

I think it's fine to fall back to the current behavior if there is not signal detected. I would expect users to keep updating the logger faster and it's not critical functionality, neither it's major critical update.
