### ISSUE TITLE
Apply sorting to the entire table

### ISSUE THREAD

**Issue by Danila89** [iterative/vscode-dvc#4620]
According to this [message](https://discord.com/channels/485586884165107732/1110155971482886195/1111364895116632195) sorting and filtering in vscode extension is only applied to the experiments under commit.
I'm using the extension as a leaderboard and it would be pretty convenient to be able to sort/filter the entire table.
<img width="750" alt="image" src="https://github.com/iterative/vscode-dvc/assets/18012372/54bad9e3-2946-4bc4-b7b5-4459ef5471f9">

**Comment by julieg18** [comment]
Filters were applied to commits in https://github.com/iterative/vscode-dvc/pull/4363, though sorting is currently only applied to experiments under commits.

**Comment by julieg18** [comment]
> I'm using the extension as a leaderboard and it would be pretty convenient to be able to sort/filter the entire table.

@Danila89, do custom plots work for your use case instead of table sorting? You can use them to compare a metric/param across all commits and experiments:

https://github.com/iterative/vscode-dvc/assets/43496356/ee65e4ac-292f-48f3-9328-87bca4679180

**Comment by Danila89** [comment]
These plots are really helpful, but it is essential for me to use some filtering of the experiments before plotting them. I didn't find the way to filter experiments before plotting them in the vscode extension.
Plots are nice in addition to sorting, not instead of it)

**Comment by julieg18** [comment]
> These plots are really helpful, but it is essential for me to use some filtering of the experiments before plotting them. I didn't find the way to filter experiments before plotting them in the vscode extension.

Filtering experiments in custom plots would be simple enough to implement! Would that enhancement work for your use case or would table sorting still be needed?

**Comment by Danila89** [comment]
It is OK like a workaround (and a very useful feature by the way), but table sorting is also nice to have

**Comment by julieg18** [comment]
Did some research for table sorting and tried a couple ideas.

### 1. Flattening then sorting the table

By flattening the table and turning off nested rows entirely, we could sort all rows from biggest to smallest and vice versa. While I don't think this would be too hard to implement on the backend, we'd need to rethink how our table would look while flattened (how do we tell what row belongs to what commit/branch). This would require some design work and adjusting our table components to handle the possibility. 

### 2. Sorting commits along with experiments

Commits would be sorted along with the experiments based on their largest (smallest could work too) value among its baseline values and its subrows' values. While this does make sorting more complicated (and probably performant since we need to parse all the table values), it is doable. I was able to get a working demo made pretty quickly. The demo is using the commit's and its subrows' max value to sort:

https://github.com/iterative/vscode-dvc/assets/43496356/a13570ad-63f9-4d84-8ff1-9ec4efc6a205

### 3. Sorting commits and branches along with experiments

Branches would be sorted similarly to how commits are sorted in idea 2 aka max value among itself and subrow's values. I also think it's doable as well but would be a bit more complicated/performant than method 2 since now we're sorting through 3 row layers instead of 2. 

What do we think? cc @shcheklein, @mattseddon

**Comment by julieg18** [comment]
As discussed in planning we've decided on working on flattening then sorting the entire table. 

Here's how the table looks flattened:

https://github.com/iterative/vscode-dvc/assets/43496356/60bb7342-76dd-473b-9d38-b894187ab935

Things to consider for this table:

- [ ] We need a way to show what sub row belongs to what. Aka what experiment row belongs to what commit belongs to what branch. One option discussed was adding an extra column that gives git information (branch/commit sha)
- [ ] There is no way to add or minus commits in branches. So far I'm not seeing a place for adding the +/- actions 🤔

**Comment by julieg18** [comment]
Finished the first iteration of the sorted table design! Demo/Images:

https://github.com/iterative/vscode-dvc/assets/43496356/8863d2cf-66d8-468a-80a2-3947b7a976d7

<img width="1097" alt="Screenshot 2023-09-20 at 11 35 38 AM" src="https://github.com/iterative/vscode-dvc/assets/43496356/1f91aff7-f446-454a-a770-e578134c6123">

<img width="423" alt="Screenshot 2023-09-20 at 11 43 26 AM" src="https://github.com/iterative/vscode-dvc/assets/43496356/dff1a350-66b4-4d2e-9801-632a6422861c">

I've added a column called "Branch/Commit" (Other options could be "Parents" or "Git Details") that gives branch/commit information and has a tooltip in the header that explains the currently missing functionality. 

I do think we'll be able to add an action somewhere for increasing/decreasing commits but I figured we could do so in a follow-up since I wasn't sure where yet. 

What do we think? cc @shcheklein

**Comment by shcheklein** [comment]
> I do think we'll be able to add an action somewhere for increasing/decreasing commits but I figured we could do so in a follow-up since I wasn't sure where yet.

Good point about the need for the action! yes, can be a followup. I don't know how to do this also. Can be a context menu in a branch column? Can be `+/-` in the column itself? We can come up with something. Can be after all a way to quickly switch back to do that for now.

> I've added a column called "Branch/Commit" (Other options could be "Parents" or "Git Details") that gives branch/commit information and has a tooltip in the header that explains the currently missing functionality.

my 2cs - let's split into Parent and Branch/Tags. Otherwise we are mixing semantics in the same column.

**Comment by julieg18** [comment]
Updated the design by splitting the "Branch/Commit" column into "Branch/Tags" and "Parent" columns:

https://github.com/iterative/vscode-dvc/assets/43496356/ab08b26b-c2d9-4de4-8bb2-ebd80f903fb4

<img width="1123" alt="Screenshot 2023-09-21 at 11 22 50 AM" src="https://github.com/iterative/vscode-dvc/assets/43496356/0f21526c-33ca-4379-aade-94f0b98ba42d">

I kept the commit/branch icons to better differentiate them from regular cell columns, but here's an quick example of how they look without the icons:

<img width="600" alt="Screenshot 2023-09-21 at 11 23 38 AM" src="https://github.com/iterative/vscode-dvc/assets/43496356/0b405dff-c3b9-457c-b9c0-d312d5767a60">

cc @shcheklein

**Comment by mattseddon** [comment]
I still have concerns over the amount of space that we'll be taking up by adding two columns instead of one. We should also note that the "parent" or "commit" column will be empty when the record is a commit. I'd suggest changing the name to baseline even if we keep them separate.

**Comment by shcheklein** [comment]
> I'd suggest changing the name to baseline even if we keep them separate.

Baseline is already used in Studio for delta / comparison mode. So, I think we should try to avoid it.

For commits we can show their actual parent commit?

**Comment by julieg18** [comment]
> We should also note that the "parent" or "commit" column will be empty when the record is a commit. 

Updated the table to make commits rows' "Parent" column blank:

<img width="886" alt="image" src="https://github.com/iterative/vscode-dvc/assets/43496356/254da4b4-be87-49a9-98d6-235c825e2afa">

> For commits we can show their actual parent commit?

Apologies, I'm not sure what you mean by "their actual parent commit". Commit rows don't have parent commits as far as I know?

**Comment by mattseddon** [comment]
@shcheklein is this what you're talking about:

<img width="852" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/cfb80d9a-58f9-4be5-8993-8f495b91c518">

The term `Baseline` is found all through the docs.

https://dvc.org/doc/user-guide/experiment-management
https://dvc.org/doc/user-guide/experiment-management/comparing-experiments
https://dvc.org/doc/studio/user-guide/experiments/run-experiments#manage-a-completed-experiment

**Comment by shcheklein** [comment]
Yes,Matt! That's the baseline that I meant.

**Comment by shcheklein** [comment]
So, I suggest not making it worse. I think parent is descriptive and applies to commits and exps, wdyt?

Overall, not a strong opinion.

**Comment by julieg18** [comment]
As of release `1.1.0`, the table now flattens when sorted, applying sorting to all rows (minus workspace):

https://github.com/iterative/vscode-dvc/assets/43496356/b1b8a945-b4e3-47de-bf58-a4331efe0af0

@Danila89, feel free to give us any feedback you have on the feature.

**Comment by Danila89** [comment]
Works for me now, thank you very much!
