### ISSUE TITLE
Allow to disable DVC datasets statuses in project Explorer

### ISSUE THREAD

**Issue by dbalabka** [iterative/vscode-dvc#4940]
I found confusing that DVC reuse the same status icons as Git does in Project Explorer. I have to check who is showing the status for the file by hovering over the icon. In my case, I use git hooks and there no need to duplicate the status in VSCode File Explorer.

Please add an option to disable this feature in the settings.

**Comment by mattseddon** [comment]
> I found confusing that DVC reuse the same status icons as Git does in Project Explorer.

Removing the statuses from File Explorer will mean that a status is not displayed at all for these files throughout the app. This is due to the limited API provided by VS Code.

<img width="1728" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/b1291643-7a4b-4e56-ac89-57c48f60731d">

<img width="1728" alt="image" src="https://github.com/iterative/vscode-dvc/assets/37993418/083fa346-ee36-4dcd-9983-5815dae72102">

Removing statuses would mean that in the second screenshot, the items would be shown under the DVC SCM tree without a status attached.

Can you please further explain your use case and why you do not need to know the status of resources tracked by DVC?
