### ISSUE TITLE
Improve UX for plots debugging 

### ISSUE THREAD

**Issue by mnrozhkov** [iterative/vscode-dvc#5087]
## Why it's important?
I spent some time helping a few teams with plot debugging.  I helped multiple teams debug their plots. When users manually configure plots in `dvc.yaml`, two types of errors are likely to appear:
1. Provided data and configuration are not compatible with the plot template (e.g pass `str` to `numerical` data type) 
2. Typos in file names 

In every case, both DVC/DVCLive are "silent". We discussed here https://github.com/iterative/dvclive/issues/750 and plan to improve.

Eventually, users open VSCode extension and don't see plots at all!   This issue aims to find a better way to notify users about problems with plots and metrics visualization in VSCode. 

## AS IS
(I don't consider VSCode extension logs, because they are not appropriate for end users) 

**1. Error messages on hovering top-level tiles** 
At this moment we provide little means for understanding the error and debugging. As an example, out [internal discussion in Slack](https://iterativeai.slack.com/archives/C01APS0FHDM/p1702045563682519?thread_ts=1702043693.214339&cid=C01APS0FHDM)  

It seems that the best means we have now is error messages in tiles with branch/exp name: 
<img width="696" alt="image" src="https://github.com/iterative/vscode-dvc/assets/11489539/d2b83df5-315b-42d6-9176-19a0e6712bef">

However 
- It's difficult to find (found this feature accidentally when trying to find smth) 
- it was not expected that tiles would show additional information for `!` sign
- for a customer who used VSCode via Dev Container to run/debug code in the remote machine, there was no message on hover `!` - but only `copy` icon. Is it expected?

**2. Error messages on hovering side menu** 
- I was not aware of them
- Takes too long to show the message on hover 
<img width="343" alt="image" src="https://github.com/iterative/vscode-dvc/assets/11489539/a92a1473-c2ac-4caf-a6c1-3f94784c8e8a">

## DISCUSSION
1. Can we show an "empty" plot for every buggy plot specified in `dvc.yaml` and show an error message on it? 
<img width="935" alt="image" src="https://github.com/iterative/vscode-dvc/assets/11489539/7bd9e561-a455-4cd4-a045-e1045e1eac78">

2. Is there another way to help with plot debugging? 
3. Can we improve documentation to mention existing features for error messages? 
4. When people open Show Plots for the first time, there is nothing inside because no experiments are selected 
   - can we select "workspace" by default? I guess it's needed most of the time.

**Comment by julieg18** [comment]
> 2. Error messages on hovering side menu
> * I was not aware of them
> * Takes too long to show the message on hover

We have no control over the side menu tooltips design but we can alter the plots webview. 

> 1. Can we show an "empty" plot for every buggy plot specified in dvc.yaml and show an error message on it?

I don't think we can easily detect when a plot is "empty", I believe we do sometimes know when an error is specific to a plot, but we always try to render the plot since some plots can render even with errors. 

> When people open Show Plots for the first time, there is nothing inside because no experiments are selected
> can we select "workspace" by default? I guess it's needed most of the time.

This is doable but it adds a layer of complexity to the experiment selection code, so it's probably not worth implementing. 

> Is there another way to help with plot debugging?
> Can we improve documentation to mention existing features for error messages?

As discussed synchronously, we can improve error messaging in the plots webview since currently all we have is the`!` in ribbon plots which is pretty subtle. I'll post some ideas.

**Comment by julieg18** [comment]
Tested some designs ideas on updating the ribbon blocks, section titles, and adding plot placeholders.

## Plot Ribbons

We can update the icon into an error icon instead of an exclamation mark.

![Screenshot 2023-12-17 at 2 52 26 PM](https://github.com/iterative/vscode-dvc/assets/43496356/0c95b80a-fc39-4fe5-8623-eb8ed54de8d1)

We can also fill the text as red but that may get a bit noisy with a project wide error:

![Screenshot 2023-12-17 at 2 52 44 PM](https://github.com/iterative/vscode-dvc/assets/43496356/9e769a90-ca77-4013-9efd-5b35d96d7cd5)
![Screenshot 2023-12-17 at 2 46 43 PM](https://github.com/iterative/vscode-dvc/assets/43496356/a78447d4-f385-4b02-ae76-6dee607b5a83)


## Section Title

Similar to ribbon blocks, we can adjust text and icons to show there are errors within the section. Hovering over would show a tooltip message with the error. 
![Screenshot 2023-12-17 at 2 50 08 PM](https://github.com/iterative/vscode-dvc/assets/43496356/7306cd35-a60e-4260-b3ca-c7b9bbd82e14)
![Screenshot 2023-12-17 at 2 50 59 PM](https://github.com/iterative/vscode-dvc/assets/43496356/38fcf5e5-8e70-4280-8f8d-e5c427cecc27)

## Plot Error Placeholders

Unlike the previous examples which are rather simple to create, I believe this would take some more time since we would need to change how our backend sends plots. 

![Screenshot 2023-12-17 at 3 31 43 PM](https://github.com/iterative/vscode-dvc/assets/43496356/ec7b1f99-336b-492f-a121-b408e759e400)

![Screenshot 2023-12-17 at 3 37 32 PM](https://github.com/iterative/vscode-dvc/assets/43496356/3ad7502e-05dd-495e-a40d-faa0714c1731)

## What to Implement

I think we should

* update the ribbon blocks, making the text red and adding the error icon
* update the section title icon to an error, showing the error in the tooltip that appears on hover

What does everyone else think? cc @shcheklein

**Comment by mnrozhkov** [comment]
Thank you @julieg18!   I really like your suggestions!  🔥 👍

**Comment by julieg18** [comment]
As discussed in #5145, we're going to leave the ribbon as is and focus on adding error messaging in the plot section.

> Can we take the idea from Studio (@sroy3 is working on errors / warnings now) - show errors in the header of the section, show a sign (yellow, green, red) nearby the section title (similar to setup screen)?
> @shcheklein in https://github.com/iterative/vscode-dvc/pull/5145#issuecomment-1867830791

Here's an example of what Studio errors look like:

![Screenshot 2023-12-22 at 5 56 11 PM](https://github.com/iterative/vscode-dvc/assets/43496356/c7d0827b-8b55-4e7c-9ace-508a06a62b42)

I believe that Studio doesn't mention what commit the error came from, just plot name and error message. I'm assuming we want to show revision as well as plot name, but that does make errors more complicated. 

Here's one design idea on what our error message would look like (open to suggestions 😅):

![Screenshot 2023-12-22 at 5 48 40 PM](https://github.com/iterative/vscode-dvc/assets/43496356/f1e193df-5f08-4ae9-a292-22d9afd170bf)

This error block would also have a collapsible option so the message doesn't get too long. What do we think? cc @shcheklein

**Comment by shcheklein** [comment]
I like it! :) thanks, @julieg18

**Comment by julieg18** [comment]
> As discussed in https://github.com/iterative/vscode-dvc/pull/5145, we're going to leave the ribbon as is and focus on adding error messaging in the plot section.

While working on this, I realized that it's not currently doable due to `dvc plots diff` not giving us the plot type of errored-out plots (see https://github.com/iterative/vscode-dvc/pull/5152#issuecomment-1874711277). Since we don't have the plot type, we don't know what plot section the error actually belongs in. 

Discussed this issue with @sroy3, and we came up with a new idea that's similar to Studio's current design. We could add a banner to the ribbon, notifying the user of errors, and once clicked on, it would open up a popup for viewing errors:

![Screenshot 2024-01-03 at 5 36 40 PM](https://github.com/iterative/vscode-dvc/assets/43496356/fc18569d-6528-4c4e-b314-f8381593e3e7)

![Screenshot 2024-01-03 at 6 00 39 PM](https://github.com/iterative/vscode-dvc/assets/43496356/439881e9-d98b-4bf2-8609-b75b55f6b5d9)

This idea is not section-specific so we can show it even if we don't know broken plot types and keeps the possibly lengthy errors from blocking the screen. What do we think? cc @shcheklein

**Comment by julieg18** [comment]
https://github.com/iterative/vscode-dvc/pull/5165 is now merged, making errors more obvious for users. Since we are unable to detect what plot types broken plots are (`dvc plots diff` does not give us this information), we currently can't implement other solutions like section messaging or "plot placeholders". 

With improving documentation covered in #5057, I think we're good to close this issue for now.

**Comment by mnrozhkov** [comment]
Thank you @julieg18 🤝
